#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <dirent.h>
#include <sys/types.h>
#include "packer.h"

static struct post posts[MAX_POSTS];
static int nr_posts;

static void sanitize_slug(char *dst, const char *src){
	while (*src) {
		if (isalnum(*src))
			*dst = *src;
		else
			*dst = '_';
		src++;
		dst++;
	}
	*dst = '\0';
}

static char *read_file(const char *path, size_t *len){
	FILE *f;
	char *buf;
	size_t sz;

	f = fopen(path, "rb");
	if (!f)
		return NULL;

	fseek(f, 0, SEEK_END);
	sz = ftell(f);
	rewind(f);

	buf = malloc(sz + 1);
	if (!buf) {
		fclose(f);
		return NULL;
	}

	if (fread(buf, 1, sz, f) != sz) {
		free(buf);
		fclose(f);
		return NULL;
	}

	buf[sz] = '\0';
	*len = sz;
	fclose(f);
	return buf;
}

static void parse_meta(char *buf, struct post *p){
	char *line = buf;
	char *next;
	char *val;
	int state = 0;

	strcpy(p->title, "Untitled");
	strcpy(p->date, "1970-01-01");

	while (line && *line) {
		next = strchr(line, '\n');
		if (next)
			*next = '\0';

		if (!strncmp(line, "---", 3)) {
			state++;
			if (state == 2)
				break;
			goto next_iter;
		}

		if (state != 1)
			goto next_iter;

		if (!strncmp(line, "title:", 6)) {
			val = line + 6;
			while (*val == ' ' || *val == '"') val++;
			strncpy(p->title, val, MAX_TITLE - 1);
			p->title[MAX_TITLE - 1] = '\0';
			val = strrchr(p->title, '"');
			if (val) *val = '\0';
		} else if (!strncmp(line, "date:", 5)) {
			val = line + 5;
			while (*val == ' ' || *val == '"') val++;
			strncpy(p->date, val, MAX_DATE - 1);
			p->date[MAX_DATE - 1] = '\0';
			val = strrchr(p->date, '"');
			if (val) *val = '\0';
		}

next_iter:
		if (!next)
			break;
		line = next + 1;
	}
}

static void dump_hex(const char *slug, const char *buf, size_t len){
	size_t i;

	printf("static const char post_data_%s[] = {\n\t", slug);
	for (i = 0; i < len; i++) {
		printf("0x%02x, ", (unsigned char)buf[i]);
		if ((i + 1) % 12 == 0)
			printf("\n\t");
	}
	printf("0x00\n};\n\n");
}

static int cmp_date(const void *a, const void *b){
	const struct post *pa = a;
	const struct post *pb = b;
	return strcmp(pb->date, pa->date);
}

int main(int argc, char **argv){
	DIR *d;
	struct dirent *de;
	char *buf;
	char *ext;
	char c_slug[MAX_SLUG];
	char *meta_buf;
	size_t len;
	int i;

	if (argc < 2)
		return 1;

	d = opendir(argv[1]);
	if (!d) {
		perror("opendir");
		return 1;
	}

	printf("/* Auto-generated by packer.c - DO NOT EDIT */\n\n");

	while ((de = readdir(d)) && nr_posts < MAX_POSTS) {
		if (!strstr(de->d_name, ".md"))
			continue;

		struct post *p = &posts[nr_posts];

		snprintf(p->path, MAX_PATH, "%s/%s", argv[1], de->d_name);
		
		strncpy(p->slug, de->d_name, MAX_SLUG - 1);
		ext = strstr(p->slug, ".md");
		if (ext) *ext = '\0';
		
		sanitize_slug(c_slug, p->slug);
		strcpy(p->slug, c_slug);

		buf = read_file(p->path, &len);
		if (!buf)
			continue;

		meta_buf = strdup(buf);
		if (meta_buf) {
			parse_meta(meta_buf, p);
			free(meta_buf);
		}

		dump_hex(p->slug, buf, len);
		free(buf);

		nr_posts++;
	}
	closedir(d);

	qsort(posts, nr_posts, sizeof(struct post), cmp_date);

	printf("/* Blog Index */\n");
	printf("const struct blog_post posts[] = {\n");
	for (i = 0; i < nr_posts; i++) {
		printf("\t{\n");
		printf("\t\t.title = \"%s\",\n", posts[i].title);
		printf("\t\t.date  = \"%s\",\n", posts[i].date);
		printf("\t\t.slug  = \"%s\"\n", posts[i].slug);
		printf("\t}%s\n", (i < nr_posts - 1) ? "," : "");
	}
	printf("};\n\n");
	
	printf("const int posts_count = %d;\n\n", nr_posts);

	printf("struct embedded_post {\n");
	printf("\tconst char *slug;\n");
	printf("\tconst char *payload;\n");
	printf("};\n\n");

	printf("static const struct embedded_post embedded_posts[] = {\n");
	for (i = 0; i < nr_posts; i++) {
		printf("\t{ \"%s\", post_data_%s },\n", 
		       posts[i].slug, posts[i].slug);
	}
	printf("\t{ NULL, NULL }\n");
	printf("};\n\n");

	printf("const char *get_article_body(const char *slug)\n{\n");
	printf("\tconst struct embedded_post *p;\n");
	printf("\tfor (p = embedded_posts; p->slug; p++)\n");
	printf("\t\tif (!strcmp(p->slug, slug))\n");
	printf("\t\t\treturn p->payload;\n");
	printf("\treturn NULL;\n}\n");

	return 0;
}
