#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>

static void print_hex(const char *path, const char *slug)
{
	FILE *f = fopen(path, "rb");
	if (!f) return;

	printf("static const char post_data_%s[] = {\n\t", slug);
	int c, count = 0;
	while ((c = fgetc(f)) != EOF) {
		printf("0x%02x, ", c);
		if (++count % 12 == 0)
			printf("\n\t");
	}
	printf("0x00\n};\n\n");
	fclose(f);
}

int main(int argc, char **argv)
{
	DIR *d;
	struct dirent *dir;
	char paths[256][512];
	char slugs[256][128];
	int i, count = 0;

	if (argc < 2)
		return 1;

	d = opendir(argv[1]);
	if (!d)
		return 1;

	printf("/* Auto-generated by packer.c - DO NOT EDIT */\n\n");

	while ((dir = readdir(d)) != NULL) {
		if (strstr(dir->d_name, ".md")) {
			char *ext;
			
			strncpy(slugs[count], dir->d_name, 127);
			ext = strstr(slugs[count], ".md");
			if (ext) *ext = '\0';

			snprintf(paths[count], 512, "%s/%s", argv[1], dir->d_name);
			
			/* Sanitize slug for C variable name */
			for (i = 0; slugs[count][i]; i++)
				if (slugs[count][i] == '-') slugs[count][i] = '_';

			print_hex(paths[count], slugs[count]);
			count++;
		}
	}
	closedir(d);

	printf("struct embedded_post {\n\tconst char *slug;\n\tconst char *data;\n};\n\n");
	printf("static const struct embedded_post embedded_posts[] = {\n");
	for (i = 0; i < count; i++) {
		char orig[128];
		char *p;
		
		p = strrchr(paths[i], '/');
		strncpy(orig, p ? p + 1 : paths[i], 127);
		p = strstr(orig, ".md");
		if (p) *p = '\0';

		printf("\t{ \"%s\", post_data_%s },\n", orig, slugs[i]);
	}
	printf("\t{ NULL, NULL }\n};\n\n");

	printf("const char *get_article_body(const char *slug)\n{\n");
	printf("\tint i;\n\tfor (i = 0; embedded_posts[i].slug; i++) {\n");
	printf("\t\tif (strcmp(embedded_posts[i].slug, slug) == 0)\n");
	printf("\t\t\treturn embedded_posts[i].data;\n\t}\n");
	printf("\treturn NULL;\n}\n");

	return 0;
}
