#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>
#include <dirent.h>
#include <sys/types.h>
#include "packer.h"

static struct post posts[MAX_POSTS];
static int nr_posts;

static bool has_markdown_extension(const char *name) {
	size_t len = strlen(name);
	return len > 3 && strcmp(name + len - 3, ".md") == 0;
}

static bool is_valid_iso_date(const char *date) {
	return strlen(date) == 10 &&
	       isdigit((unsigned char)date[0]) &&
	       isdigit((unsigned char)date[1]) &&
	       isdigit((unsigned char)date[2]) &&
	       isdigit((unsigned char)date[3]) &&
	       date[4] == '-' &&
	       isdigit((unsigned char)date[5]) &&
	       isdigit((unsigned char)date[6]) &&
	       date[7] == '-' &&
	       isdigit((unsigned char)date[8]) &&
	       isdigit((unsigned char)date[9]);
}

static void fail(const char *msg, const char *detail) {
	fprintf(stderr, "%s: %s\n", msg, detail ? detail : "");
	exit(1);
}

static void copy_string(char *dst, size_t dst_cap, const char *src, const char *field) {
	size_t len = strlen(src);
	if (len >= dst_cap)
		fail("value exceeds fixed buffer", field);
	memcpy(dst, src, len + 1);
}

static void sanitize_slug(char *dst, size_t dst_cap, const char *src){
	size_t i = 0;
	while (*src) {
		if (i + 1 >= dst_cap)
			fail("slug exceeds fixed buffer", src);
		if (isalnum((unsigned char)*src))
			dst[i] = *src;
		else
			dst[i] = '_';
		src++;
		i++;
	}
	dst[i] = '\0';
}

static char *read_file(const char *path, size_t *len){
	FILE *f;
	char *buf;
	size_t sz;

	f = fopen(path, "rb");
	if (!f)
		return NULL;

	fseek(f, 0, SEEK_END);
	sz = ftell(f);
	rewind(f);

	buf = malloc(sz + 1);
	if (!buf) {
		fclose(f);
		return NULL;
	}

	if (fread(buf, 1, sz, f) != sz) {
		free(buf);
		fclose(f);
		return NULL;
	}

	buf[sz] = '\0';
	*len = sz;
	fclose(f);
	return buf;
}

static void extract_value(char *dest, const char *src, size_t max){
	while (*src && (isspace((unsigned char)*src) || *src == '\x22'))
		src++;

	strncpy(dest, src, max - 1);
	dest[max - 1] = '\0';

	size_t len = strlen(dest);
	if (len == 0)
		return;

	char *end = dest + len - 1;
	while (end >= dest && (isspace((unsigned char)*end) || *end == '\x22')) {
		*end = '\0';
		end--;
	}
}

static void parse_meta(const char *buf, struct post *p){
	const char *line = buf;
	const char *next;

	struct {
		const char *key;
		char *dest;
		size_t len;
	} map[] = {
		{ "title:",       p->title,       MAX_TITLE },
		{ "date:",        p->date,        MAX_DATE },
		{ "description:", p->description, MAX_DESCRIPTION },
		{ NULL, NULL, 0 }
	};

	strcpy(p->title, "Untitled");
	strcpy(p->date, "1970-01-01");
	p->description[0] = '\0';

	if (strncmp(line, "---", 3) != 0 || (line[3] != '\n' && line[3] != '\r'))
		return;

	line = strchr(line, '\n');
	if (!line)
		return;
	line++;

	while (line && *line) {
		next = strchr(line, '\n');
		size_t line_len = next ? (size_t)(next - line) : strlen(line);

		if ((line_len == 3 && strncmp(line, "---", 3) == 0) ||
		    (line_len == 4 && strncmp(line, "---\r", 4) == 0)) {
			break;
		}

		for (int i = 0; map[i].key; i++) {
			size_t klen = strlen(map[i].key);
			if (line_len >= klen && strncmp(line, map[i].key, klen) == 0) {
				char temp[1024];
				size_t copy_len = line_len - klen;
				if (copy_len >= sizeof(temp))
					fail("front matter line exceeds parser buffer", map[i].key);
				memcpy(temp, line + klen, copy_len);
				temp[copy_len] = '\0';
				extract_value(map[i].dest, temp, map[i].len);
				break;
			}
		}

		line = next ? next + 1 : NULL;
	}
}

static void dump_hex(const char *slug, const char *buf, size_t len){
	size_t i;

	printf("static const char post_data_%s[] = {\n\t", slug);
	for (i = 0; i < len; i++) {
		printf("0x%02x, ", (unsigned char)buf[i]);
		if ((i + 1) % 12 == 0)
			printf("\n\t");
	}
	printf("0x00\n};\n\n");
}

static int cmp_date(const void *a, const void *b){
	const struct post *pa = a;
	const struct post *pb = b;
	return strcmp(pb->date, pa->date);
}

static int cmp_slug_post_index(const void *a, const void *b) {
	const int ia = *(const int *)a;
	const int ib = *(const int *)b;
	return strcmp(posts[ia].slug, posts[ib].slug);
}

static void emit_c_string(const char *s) {
	const unsigned char *p = (const unsigned char *)s;

	putchar('"');
	while (*p) {
		switch (*p) {
		case '\\': fputs("\\\\", stdout); break;
		case '"': fputs("\\\"", stdout); break;
		case '\n': fputs("\\n", stdout); break;
		case '\r': fputs("\\r", stdout); break;
		case '\t': fputs("\\t", stdout); break;
		default:
			if (*p < 0x20) {
				printf("\\x%02x", *p);
			} else {
				putchar(*p);
			}
		}
		p++;
	}
	putchar('"');
}

int main(int argc, char **argv){
	DIR *d;
	struct dirent *de;
	char *buf;
	char *ext;
	char c_slug[MAX_SLUG];
	size_t len;
	int slug_order[MAX_POSTS];
	int i;

	if (argc < 2)
		return 1;

	d = opendir(argv[1]);
	if (!d) {
		perror("opendir");
		return 1;
	}

	printf("/* Auto-generated by packer.c - DO NOT EDIT */\n\n");

	while ((de = readdir(d)) && nr_posts < MAX_POSTS) {
		if (!has_markdown_extension(de->d_name))
			continue;

		struct post *p = &posts[nr_posts];

		if (snprintf(p->path, MAX_PATH, "%s/%s", argv[1], de->d_name) >= MAX_PATH)
			fail("path exceeds fixed buffer", de->d_name);
		
		copy_string(p->slug, MAX_SLUG, de->d_name, "slug");
		ext = strstr(p->slug, ".md");
		if (ext) *ext = '\0';
		
		sanitize_slug(c_slug, sizeof(c_slug), p->slug);
		copy_string(p->slug, MAX_SLUG, c_slug, "slug");

		buf = read_file(p->path, &len);
		if (!buf)
			continue;

		parse_meta(buf, p);
		if (!is_valid_iso_date(p->date))
			fail("date must be in YYYY-MM-DD format", p->path);

		dump_hex(p->slug, buf, len);
		free(buf);

		nr_posts++;
	}
	closedir(d);

	qsort(posts, nr_posts, sizeof(struct post), cmp_date);

	printf("/* Blog Index */\n");
	printf("const struct blog_post posts[] = {\n");
	for (i = 0; i < nr_posts; i++) {
		printf("\t{\n");
		printf("\t\t.title = ");
		emit_c_string(posts[i].title);
		printf(",\n");
		printf("\t\t.date  = ");
		emit_c_string(posts[i].date);
		printf(",\n");
		printf("\t\t.slug  = ");
		emit_c_string(posts[i].slug);
		printf(",\n");
		printf("\t\t.description = ");
		emit_c_string(posts[i].description);
		printf("\n");
		printf("\t}%s\n", (i < nr_posts - 1) ? "," : "");
	}
	printf("};\n\n");
	
	printf("const int posts_count = %d;\n\n", nr_posts);

	for (i = 0; i < nr_posts; i++)
		slug_order[i] = i;
	qsort(slug_order, nr_posts, sizeof(int), cmp_slug_post_index);

	printf("static const struct { const char *slug; int index; } post_slug_index[] = {\n");
	for (i = 0; i < nr_posts; i++) {
		printf("\t{ ");
		emit_c_string(posts[slug_order[i]].slug);
		printf(", %d }%s\n", slug_order[i], (i < nr_posts - 1) ? "," : "");
	}
	printf("};\n\n");

	printf("int find_post_index_by_slug(const char *slug)\n{\n");
	printf("\tint lo = 0;\n");
	printf("\tint hi = posts_count - 1;\n\n");
	printf("\twhile (lo <= hi) {\n");
	printf("\t\tint mid = lo + ((hi - lo) >> 1);\n");
	printf("\t\tint cmp = strcmp(slug, post_slug_index[mid].slug);\n\n");
	printf("\t\tif (cmp == 0)\n");
	printf("\t\t\treturn post_slug_index[mid].index;\n");
	printf("\t\tif (cmp < 0)\n");
	printf("\t\t\thi = mid - 1;\n");
	printf("\t\telse\n");
	printf("\t\t\tlo = mid + 1;\n");
	printf("\t}\n\n");
	printf("\treturn -1;\n");
	printf("}\n\n");

	printf("const char *get_article_body(int index)\n{\n");
	printf("\tif (index < 0 || index >= posts_count)\n");
	printf("\t\treturn NULL;\n");
	printf("\tswitch(index) {\n");
	for (i = 0; i < nr_posts; i++) {
		printf("\t\tcase %d: return post_data_%s;\n", i, posts[i].slug);
	}
	printf("\t\tdefault: return NULL;\n\t}\n}\n");

	return 0;
}
